[build]
  command = "turbo run build"
  publish = "apps/next-app/.next"

[[build.environment]]
  NODE_VERSION = "18"  # or your project's Node.js version

# Define separate deploy contexts (optional)
# Netlify will build the apps in order and deploy them correctly

# Next.js settings (for Next.js plugin support)
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect Angular routes to index.html for SPA behavior
[[redirects]]
  from = "/angular-app/*"
  to = "/angular-app/index.html"
  status = 200

